[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "car-ros2-env"
version = "0.0.1"
description = "RL envs for car dynamics"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["rl_env"]


